error TS2322: Type '{ name: string; size: number; className: string; }' is not assignable to type 'IntrinsicAttributes & UserAvatarProps'.||Property 'className' does not exist on type 'IntrinsicAttributes & UserAvatarProps'. err fixed